# Generated by Django 5.1.6 on 2025-02-18 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowingrecord',
            options={'ordering': ['-borrowed_on']},
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='borrowed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='due_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
